name: auth_for_perception
description: Drop-in auth components for perception.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  
  core_of_perception: ^0.0.0-a1
  error_handling_for_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  navigation_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1
  
  firebase_auth_service_interface: ^0.0.0-a1
  firebase_auth_service_flutterfire: ^0.0.0-a1

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints: ^0.0.0-a1
  build_runner: ^2.4.5
  builders_for_perception: ^0.0.0-a1
  test_utils_for_perception: ^0.0.0-a1
